### ISSUE TITLE
Refreshing playlist automatically

### ISSUE THREAD

**Issue by fm4d** [pft/mingus#17]
It would be really nice to have mingus refreshing playlist automatically, for example after song ends or on mpd toggle, having to do it manually with 'g' is not very pleasant.

**Comment by pft** [comment]
This is fixed in the Mopidy branch, using the mpd idle / noidle command. It may still have a little latency though.

The Mopidy branch does have differences in the way how it shows the playlist and browse buffer, namely, in a column layout, which I am not sure everybody likes, though I like it myself a lot.

This column layout is relative to the buffers width, which does not by default react to buffer size changes, which is a bit of a fundamental issue, as we can in Emacs have different buffers showing the same contents.

I have created [a gist](https://gist.github.com/pft/684603b6cc2856e41ac1) to resolve that issue that works just fine if you have no more than one buffer showing the playlist and the bufffer, so we have truly responsive layout.

Please check out the Mopidy branch and report back to me if you like it; I would like to merge all that stuff back soon, but am a tad uncertain about the reception.

**Comment by nsemrau** [comment]
I've been using the Mopidy branch since it became available. I appreciate the new features and clean-ups of the code base, they made switch back to Mingus as my main music player. So a hearty :+1: for merging this branch from me.

**Comment by pft** [comment]
Thanks @nsemrau .

I just merged the mopidy branch. See commit https://github.com/pft/mingus/commit/826a2b536b73a24c22e73ea92d3deba2bffa1ad1.
