### ISSUE TITLE
Mingus keeps ressurecting `*Mingus*` window even when buffer killed

### ISSUE THREAD

**Issue by dakrone** [pft/mingus#20]
If I open Mingus at any point in Emacs being opened and play some music, then kill the buffer, whenever I quit a different buffer with `quit-buffer` (say magit, elfeed, or my emacs mail client), `*Mingus*` pops back up as an empty buffer that looks like:

![screenshot from 2016-03-10 10-04-55](https://cloud.githubusercontent.com/assets/19060/13677537/923cbfd8-e6a7-11e5-8c53-45636bab6198.png)

I can kill it (again), but the next time I quit or kill a buffer it pops right back up again.

I've also noticed while typing in some buffers, for a split second, mingus seems to pop itself up to the front and then hide itself again.

Is there some sort of timer or hook that mingus is adding that is doing this? This has only been occurring recently (when mingus started switching to the new playlist look and feel)

**Comment by pft** [comment]
Hi Lee, thanks for your report. I just fixed this in 826a2b536b73a24c22e73ea92d3deba2bffa1ad1. The culprit was the invocation of `mingus-set-NP-mark` inside `mingus-timer-handler`.

I do not know whether the 'split-second pop-up' is also fixed by this (couldn't reproduce), but the commit made sure `mingus-set-NP-mark` is not called by the timer when the buffer isn't visible. The timer does however still update the playlist if the playlist itself has changed, though this only if the buffer is still live.

Also note that the interval is now customizable, through `mingus-timer-interval` (default 1 sec).

**Comment by dakrone** [comment]
Thanks for fixing this @pft , I haven't seen it since!

**Comment by dakrone** [comment]
And thanks for Mingus, it's a nice UI!
